### ISSUE TITLE
Makefile issue(?)

### ISSUE THREAD

**Issue by Reisyukaku** [44670/NTR#6]
Seems due to the nature of bootloader.s, you need -pie passed to the linker. But that only solves half the problem. With -pie, the payload can run and everything is fine up till BootNTR says 'exiting...' then it crashes and ntr menu doesnt work.

**Comment by 44670** [comment]
-pie is not required, since it will relocate itself before jumping to c_entry (in bootloader.s)

**Comment by Reisyukaku** [comment]
well with a clean clone, it doesnt jump to ntr payload at all unless i add that. I compared the elfs of makefile compiled and python compiled to see why only python one works and it shows differences in the bootloader, specifically __rel_dyn_start and stuff.

**Comment by profi200** [comment]
The builds with the new makefile are (still?) untested. So no surprise you are running into problems.

**Comment by 44670** [comment]
Sorry I was wrong, -pie was required for linker
